### ISSUE TITLE
little problem

### ISSUE THREAD

**Issue by fwf02** [nanolopez84/winlogonKiller#1]
do u know how to bypass the sign out when winlogon process killed?

**Comment by nanolopez84** [comment]
Hi, it's been a while since I don't need to use this anymore, so let me check and I will come back to you.

**Comment by fwf02** [comment]
oright thank you so much

**Comment by nanolopez84** [comment]
Ok, I tested it again, and if you asked about killing the winlogon but avoiding the OS to signout I'm afraid I don't know if that is possible, because I've been working with Credential Providers and Security Packages and I needed them to be reloaded without restarting the operative system, that's how I came up with this program (winlogonKiller).
Credential Providers are launched each time the LogonUI process start, so by replacing the .dll it will be updated the next time you signout, but Security Packages live the entire lifecycle since the OS starts until it restarts and they are loaded by the winlogon process, so **by killing winlogon (which acts as the session manager for the OS), it will be spawn again automatically by the OS with the updated Security Package, and forcing the user to start a new session, hence the signout**.
Hope this clarified the scenario.
